name: Deploy to Github Pages

on:
   push:
    branches: [ "Feat/ErroBranchDeploy" ]
   pull_request:
    branches: [ "Feat/ErroBranchDeploy" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    
    - name: Publish Application
      run: dotnet publish -c Release ./BlazorWasm/BlazorWasm.csproj
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./BlazorWasm/bin/Release/net6.0/publish/wwwroot/
           

